{
 "title": "Checks (Real time)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "checks",
    "query": "select name from checks where active = true;"
   }
  ]
 },
 "panels": [
  {
   "title": "Checks (Real-time)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select name,\r\nCASE WHEN now()<next_check_schedule THEN last_check_status ELSE 3 end as current_state,\r\nEXTRACT(EPOCH FROM (now() - last_check_status_changed )) as enlapsed, \r\nCASE WHEN now()<next_check_schedule THEN last_check_text ELSE 'STALE' end as last_check_text\r\nfrom checks\r\nORDER BY name;\r\n"
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\", name,\n  text,\n  status_to as status\nFROM status_change_history sch\nJOIN checks c ON c.id = sch.check_id\nWHERE $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "$checks",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 19 },
     "repeat": "checks",
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "select 123 as time,\r\nCASE WHEN now()<next_check_schedule THEN last_check_status ELSE 3 end as current_state\r\nfrom checks\r\nwhere name = $checks;"
      }
     ]
    },
    {
     "title": "$checks",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "select 123 as time,\r\nCASE WHEN now()<next_check_schedule THEN last_check_status ELSE 3 end as current_state\r\nfrom checks\r\nwhere name = $checks;"
      }
     ]
    },
    {
     "title": "$checks",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "select 123 as time,\r\nCASE WHEN now()<next_check_schedule THEN last_check_status ELSE 3 end as current_state\r\nfrom checks\r\nwhere name = $checks;"
      }
     ]
    }
   ]
  }
 ]
}